### ISSUE TITLE
TODO pour Kings Canyon

### ISSUE THREAD

**Issue by sarahmamy** [bensarah/escapades#10]
To do :
- [x] résoudre le bug de centrage de la map
- [x]  rajouter Seville Lake, Mitchell Peak --> les points d'intérêt au JSON de la rando (pour que la carte soit jolie)
- [x] coder l'action qui highlighte une certaine partie du trajet
- [x] résoudre les soucis sur l'ordi de Sarah (emoji s'affichent mal + photos s'affichent retard + taille d'une section plus grande verticalement que l'espace sur navigateur)
- [x] Footer
- [x] Favicon 
- [ ] faire la section 'summary' avec tags & chiffres
- [x] rajouter tous les points sur l'elevation graph (bcp + de granularité sur le graphe)
- [x] enlever l'appel à l'API Mapbox
- [x] Trouver un formatting pour 'Simon 9 ans' 
- [x] rajouter le mesh gradient aux photos d'entrée
