### ISSUE TITLE
Todo list lancement V1

### ISSUE THREAD

**Issue by benjamintd** [bensarah/escapades#40]
Tu peux éditer ce post directement si tu vois autre chose. 

J'essaye de catégoriser les choses _nécessaires_ pour être fiers d'envoyer ça par mail à nos parents :) 

Ca va exclure plusieurs améliorations UX/UI mais j'essaye de catégoriser le minimum syndical ici!

- [x] Avoir une page About #19 
- [x] Être lisible sur mobile #22, #56 
- [x] Résoudre le bug des photos #30 
- [x] Labels supplémentaires sur la carte #38 
- [x] Avoir au moins 5 randos, si possible 2 en France #3
  - [x] Mitchell
  - [x] Half Dome
  - [x] Whitney
  - [ ] Lances de Malissard
  - [ ] Desolation Wilderness
  - [x] Trois Seigneurs
  

Je vois rien d'autre de bloquant?
